### PR TITLE
proposal: update examples with short functions

### PR DESCRIPTION
**Pull request by chris-kruining**
I think showing the short function syntax in the examples might improve the clarity of the examples because there is less visual bloat for the eye to process.

I you don't agree, just close the PR, no worries.

### CODE REVIEW

**Comment by glensc** [comment]
This is not valid syntax for the minimum php version the library supports (7.2):
- https://github.com/silexphp/Pimple/blob/v3.5.0/composer.json#L15

**Comment by derrabus** [comment]
> This is not valid syntax for the minimum php version the library supports (7.2):

Correct, but is that a problem?

**Comment by glensc** [comment]
It's up to maintainers to decide is that a problem, if I would be the maintainer I wouldn't put code to documentation that doesn't always run. it's just asking for support trouble explaining you need yadauyada.

A similar change was rejected in the past, and in that case, the syntax change required PHP 5.4 that matched the supported PHP version (7.2) at that time:
- https://github.com/silexphp/Pimple/pull/254

**Comment by glensc** [comment]
Also, read the caution in project README:

> 
> Pimple
> Caution!
> 
> Pimple is now closed for changes. No new features will be added and no cosmetic changes will be accepted either. The only accepted changes are compatibility with newer PHP versions and security issue fixes.
> 
> Caution!

**Comment by fabpot** [comment]
I think it's a bit different from the other PR that was rejected. First, it makes things way more readable, and then, 7.2 is not maintained anymore for a very long time.

**Comment by fabpot** [comment]
Also, it only changes the README, not the code.

**Comment by fabpot** [comment]
Thank you @chris-kruining.

**Pull request merged**
