### PR TITLE
Added PSR-11 wrapper

### PR DESCRIPTION
**Pull request by skalpa**
Adds a PSR-11 wrapper that can be used to access the content of a Pimple container using `Psr\Container\ContainerInterface`.

I know that since #222 implementing such a wrapper is trivial, however I still believe it makes sense to provide one. The class is `final`, so I guess the maintenance costs won't be too high.

If this gets accepted, I'll also add a service provider and an `ArgumentValueResolver` to Silex so users can do:
```php
$app->get('/route', function (Psr\Container\ContainerInterface $container) {
});
```

The implementations (C and PHP) are ready to review, I'll add the documentation and ping you once it's ready to merge.

### CODE REVIEW

**Comment by stof** [comment]
As the new PSR-11 container is purely a wrapper around Pimple, I would not bother implementing it in C. Maintenance will be easier if it stays in userland only (and all the performance-sensitive code is in `Pimple\Container` anyway)

**Comment by fabpot** [comment]
I agree with @stof, especially now that the C version is deprecated anyway.

**Comment by skalpa** [comment]
Just to be the devil's advocate: the advantage of the C implementation is that it came with absolutely no performance cost as opposed to the userland implementation that requires an additional PHP method call (in C I could directly call `pimple_object_read_dimension` and bypass the `offsetGet` PHP method).

Anyway, I'm :+1:  to not having to maintain it, so I removed the C implementation and amended the documentation.

Should be good to go.

**Comment by fabpot** [comment]
Thank you @skalpa.

**Pull request closed without merging**
