### PR TITLE
Use absolute function reference

### PR DESCRIPTION
**Pull request by rullzer**
See https://github.com/Roave/FunctionFQNReplacer

### CODE REVIEW

**Comment by glensc** [comment]
the performance impact is non-existent. why even bother to sacrifice readability?

**Comment by fabpot** [comment]
Indeed, that does not change anything in terms of performance. So, I'm going to close this one. Thanks for your pull request.

**Comment by yriveiro** [comment]
@rullzer did a benchmark that shows an improvement, i will not say if it's enough or if it worth the work, but he shows numbers and an explanation of his research.

@glensc did an statement that the performance impact is non-existent without number or any explanation and @fabpot (creator of pimple) agree with @glensc , no explanation no number.

My question here is: why we don't have any kind of performance gain if we execute less opcodes?

I really want to know, because I have and application that runs in 50 machines with tons of threads, if this makes me save 0.5% of cpu time per second in each CPU, all together it's a big number ...

**Comment by fabpot** [comment]
If someone can prove that it makes things faster, I would be happy to merge this. /cc @nicolas-grekas, @jpauli

**Comment by jpauli** [comment]
It is faster, if it is run several hundreds/thousands of times per request.

If such a code is run once per request, it is irrelevant

**Comment by nicolas-grekas** [comment]
Most functions *do not* benefit from root-prefixes.
A short list of them *do*: see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048 for background. But of course, the benefit exists only in tight loops, where calls are make x10k times.

**Comment by rullzer** [comment]
I ran some numbers, a default propfind in Nextcloud on my test setup does 2016 calls to `Pimple\Container::offsetGet`.

This requests takes there about 165ms. 

According to blackfire the time spend in `Pimple\Container::offsetGet`

Before: 19.36 ms
After: 17.93 ms

Diff: 1.43 ms

Now I know I'll probably also me measuring a bit of noise. But >1ms on a 165ms requiest seems not insignificant.

Disclaimer: I tested this on my development machine. Which probably means: hot cache, hot opcache, fast SSD, fast RAM, fast CPU etc.

**Comment by fabpot** [comment]
Thank you @rullzer.

**Comment by fabpot** [comment]
released in 3.2.3

**Comment by glensc** [comment]
instead of prefixing, would importing functions have same result?

**Comment by nicolas-grekas** [comment]
Not on PHP 5.3, which is the lowest version supported here.

**Pull request merged**
