### PR TITLE
Fix typo!

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by stof** [comment]
Actually, passing 2 separate arguments is perfectly valid in composer (except that you may need to escape the ``~3.0`` argument in case your shell always treats ``~`` at the beginning of an argument as ``$HOME``)

**Comment by ovr** [comment]
@stof 
I am using `zsh` and with space it's not working
I think this variant is better to use

**Comment by stof** [comment]
Well, zsh is expanding ``~`` to ``$HOME``, so it needs quoting. It is one of the case I mentionned

**Comment by fabpot** [comment]
fixed 53afbb6

**Pull request closed without merging**
