### PR TITLE
Add Property Access interface

### PR DESCRIPTION
**Pull request by glensc**
Inspired by [mrclay/props-dic](https://github.com/mrclay/Props) making Pimple IDE friendly.

```php
/**
 * @property-read string $style
 * @property-read Dough  $dough
 * @property-read Cheese $cheese
 * @property-read Pizza  $pizza
 * @method        Slice  new_slice()
 */
```

see more:
 - https://github.com/mrclay/Props#pimple-with-property-access
 - https://github.com/mrclay/Props/blob/2.2.0/scripts/example-pimple.php

### CODE REVIEW

**Comment by stof** [comment]
IIRC, this has already been rejected in the past

**Comment by glensc** [comment]
can you find that discussion?

i wonder can github filter "closed" PR's that are not "merged"

**Comment by glensc** [comment]
found something (still searching) #1 -  but it only says like the changes were pushed, but no information about commit ids

**Comment by glensc** [comment]
Perhaps implement only `__get` method (as that is what I need), would that be accepted more eagerly?

**Comment by glensc** [comment]
with this project living again (psr11 changes etc) perhaps this topic can be re-visited?

**Comment by glensc** [comment]
Perhaps add a new class like with [Psr11] was added, that's kind of this file, but in this repository:
- https://github.com/mrclay/Props/blob/3.0.0/src/Props/Pimple.php

[Psr11]: https://github.com/silexphp/Pimple/blob/v3.3.0/src/Pimple/Psr11/Container.php

**Comment by fabpot** [comment]
Closing this PR as Pimple is now closed for changes.

**Pull request closed without merging**
